project:
  type: website

website:
  title: "R Coding Club"
  site-url: "https://coding-club.rostools.org"
  navbar:
    right:
      - icon: github
        href: https://github.com/rostools/coding-club
      - icon: youtube
        href: https://www.youtube.com/@r-cubedcodingclub-bc5bf
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.html
      - text: "Code of Conduct"
        href: "https://guides.rostools.org/conduct.html"

format:
  r3-theme-html:
    include-before-body:
      - "includes/site-counter.html"

editor:
  markdown:
    wrap: 72
    canonical: true
