project:
  type: website

website:
  title: "Coding Club"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rostools/coding-club
format:
  html:
    theme: cosmo
    css: styles.css
    fig-align: center

editor:
  markdown:
    wrap: 72
    canonical: true
